osx_image: xcode9.4
language: objective-c
branches:
  only:
    - master
before_install:
    - gem install xcpretty
before_script:
    - set -o pipefail
script:
    - swiftlint
    - xcodebuild test -project ./Montblanc.xcodeproj -scheme MontblancTests -configuration Debug -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=11.4,name=iPhone X' | xcpretty -c
    - xcodebuild -project ./Montblanc.xcodeproj -scheme 'Montblanc OSX' -configuration Debug | xcpretty -c
